### ISSUE TITLE
Spelling mistake in readme.md

### ISSUE THREAD

**Issue by osaf96** [mkm-dz/otterbrass#46]
hello guys, I don't know if i should report this as an issue or not, I was checking out the repository and found a spelling mistake. 
I'm attaching the screenshot here. it's written suscribed which i feel like should be subscribed

![image](https://user-images.githubusercontent.com/22621352/174952995-ca0b0822-42eb-45be-8660-a5a2bed09b02.png)

**Comment by mkm-dz** [comment]
thanks for the report :), it has been fixed.
